[package]
name = "common"
version = "0.0.1"
edition = "2024"

[features]
default = []
std = ["embassy-time/std", "critical-section/std", "rand/std"]

[dependencies]
critical-section = { version = "1.2.0" }
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
spin = { version = "0.9", default-features = false, features = ["mutex", "rwlock", "spin_mutex"] }
embassy-sync = { version = "0.7.2", default-features = false }
embassy-time = { version = "0.5.0", default-features = false }
libm = { version = "0.2.16", default-features = false }
