[package]
name = "common"
version = "0.0.1"
edition = "2024"

[features]
default = ["std"]
std = []

[dependencies]
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
spin = { version = "0.9", default-features = false, features = ["mutex", "rwlock", "spin_mutex"] }
embassy-sync = "0.7.2"
embassy-time = "0.5.0"
libm = "0.2.16"
